// This file was generated automatically using "ifc-syntax-codegen"
//
// Licensed under MIT by Alan Rynne
//
// Contains the following entities:
//    - IfcEvaporativeCoolerTypeEnum

enum IfcEvaporativeCoolerTypeEnum {
    DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER,
    DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER,
    DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER,
    DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER,
    DIRECTEVAPORATIVEAIRWASHER,
    INDIRECTEVAPORATIVEPACKAGEAIRCOOLER,
    INDIRECTEVAPORATIVEWETCOIL,
    INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER,
    INDIRECTDIRECTCOMBINATION,
    USERDEFINED,
    NOTDEFINED
}
export default IfcEvaporativeCoolerTypeEnum