// This file was generated automatically using "ifc-syntax-codegen"
//
// Licensed under MIT by Alan Rynne
//
// Contains the following entities:
//    - IfcExtrudedAreaSolidTapered

import { IfcProfileDef, IfcAxis2Placement3D, IfcDirection, IfcExtrudedAreaSolid } from './'
import { IfcPositiveLengthMeasure } from '../types'

/** IfcExtrudedAreaSolidTapered is defined by sweeping a cross section along a linear spine.
 *
 * The cross section may change along the sweep from the shape of the start cross section into the shape of the end cross section.
 *
 * The resulting solid is bounded by three or more faces: A start face, an end face (each defined by start and end planes and sections), and one or more lateral faces.
 *
 * Each lateral face is a ruled surface defined by a pair of corresponding edges of the start and end section
 *
 * The linear spine is defined by:The start cross section is defined by SELF\IfcSweptAreaSolid
 *
 * SweptArea:The end cross section is defined by EndSweptArea:In case of two parameterized profiles the shape is constructed as follows:In case of Cartesian transformation of the start cross section the shape is constructed as follows:Informal Propositions:
 */
 class IfcExtrudedAreaSolidTapered extends IfcExtrudedAreaSolid {
    constructor(SweptArea:IfcProfileDef, Position:IfcAxis2Placement3D, ExtrudedDirection:IfcDirection, Depth:IfcPositiveLengthMeasure, EndSweptArea:IfcProfileDef) {
        super(SweptArea, Position, ExtrudedDirection, Depth)
        this.EndSweptArea = EndSweptArea
    }
    /** The surface defining the end of the swept area.
     * It is given as a profile definition.
     * The position coordinate system of the EndSwptArea is generated by translating the SELF\IfcSweptAreaSolid
     * Position along the SELF\IfcExtrudedAreaSolid
     * ExtrudedDirection by the distance of SELF\IfcExtrudedAreaSolid.Depth.
    */
    EndSweptArea: IfcProfileDef
}

export default IfcExtrudedAreaSolidTapered