// This file was generated automatically using "ifc-syntax-codegen"
//
// Licensed under MIT by Alan Rynne
//
// Contains the following entities:
//    - IfcDerivedUnitEnum

enum IfcDerivedUnitEnum {
    ANGULARVELOCITYUNIT,
    COMPOUNDPLANEANGLEUNIT,
    DYNAMICVISCOSITYUNIT,
    HEATFLUXDENSITYUNIT,
    INTEGERCOUNTRATEUNIT,
    ISOTHERMALMOISTURECAPACITYUNIT,
    KINEMATICVISCOSITYUNIT,
    LINEARVELOCITYUNIT,
    MASSDENSITYUNIT,
    MASSFLOWRATEUNIT,
    MOISTUREDIFFUSIVITYUNIT,
    MOLECULARWEIGHTUNIT,
    SPECIFICHEATCAPACITYUNIT,
    THERMALADMITTANCEUNIT,
    THERMALCONDUCTANCEUNIT,
    THERMALRESISTANCEUNIT,
    THERMALTRANSMITTANCEUNIT,
    VAPORPERMEABILITYUNIT,
    VOLUMETRICFLOWRATEUNIT,
    ROTATIONALFREQUENCYUNIT,
    TORQUEUNIT,
    MOMENTOFINERTIAUNIT,
    LINEARMOMENTUNIT,
    LINEARFORCEUNIT,
    PLANARFORCEUNIT,
    MODULUSOFELASTICITYUNIT,
    SHEARMODULUSUNIT,
    LINEARSTIFFNESSUNIT,
    ROTATIONALSTIFFNESSUNIT,
    MODULUSOFSUBGRADEREACTIONUNIT,
    ACCELERATIONUNIT,
    CURVATUREUNIT,
    HEATINGVALUEUNIT,
    IONCONCENTRATIONUNIT,
    LUMINOUSINTENSITYDISTRIBUTIONUNIT,
    MASSPERLENGTHUNIT,
    MODULUSOFLINEARSUBGRADEREACTIONUNIT,
    MODULUSOFROTATIONALSUBGRADEREACTIONUNIT,
    PHUNIT,
    ROTATIONALMASSUNIT,
    SECTIONAREAINTEGRALUNIT,
    SECTIONMODULUSUNIT,
    SOUNDPOWERUNIT,
    SOUNDPRESSUREUNIT,
    TEMPERATUREGRADIENTUNIT,
    THERMALEXPANSIONCOEFFICIENTUNIT,
    WARPINGCONSTANTUNIT,
    WARPINGMOMENTUNIT,
    USERDEFINED
}
export default IfcDerivedUnitEnum