// This file was generated automatically using "ifc-syntax-codegen"
//
// Licensed under MIT by Alan Rynne
//
// Contains the following entities:
//    - IfcDerivedMeasureValue

enum IfcDerivedMeasureValue {
    IfcVolumetricFlowRateMeasure,
    IfcTimeStamp,
    IfcThermalTransmittanceMeasure,
    IfcThermalResistanceMeasure,
    IfcThermalAdmittanceMeasure,
    IfcPressureMeasure,
    IfcPowerMeasure,
    IfcMassFlowRateMeasure,
    IfcMassDensityMeasure,
    IfcLinearVelocityMeasure,
    IfcKinematicViscosityMeasure,
    IfcIntegerCountRateMeasure,
    IfcHeatFluxDensityMeasure,
    IfcFrequencyMeasure,
    IfcEnergyMeasure,
    IfcElectricVoltageMeasure,
    IfcDynamicViscosityMeasure,
    IfcCompoundPlaneAngleMeasure,
    IfcAngularVelocityMeasure,
    IfcThermalConductivityMeasure,
    IfcMolecularWeightMeasure,
    IfcVaporPermeabilityMeasure,
    IfcMoistureDiffusivityMeasure,
    IfcIsothermalMoistureCapacityMeasure,
    IfcSpecificHeatCapacityMeasure,
    IfcMonetaryMeasure,
    IfcMagneticFluxDensityMeasure,
    IfcMagneticFluxMeasure,
    IfcLuminousFluxMeasure,
    IfcForceMeasure,
    IfcInductanceMeasure,
    IfcIlluminanceMeasure,
    IfcElectricResistanceMeasure,
    IfcElectricConductanceMeasure,
    IfcElectricChargeMeasure,
    IfcDoseEquivalentMeasure,
    IfcElectricCapacitanceMeasure,
    IfcAbsorbedDoseMeasure,
    IfcRadioActivityMeasure,
    IfcRotationalFrequencyMeasure,
    IfcTorqueMeasure,
    IfcAccelerationMeasure,
    IfcLinearForceMeasure,
    IfcLinearStiffnessMeasure,
    IfcModulusOfSubgradeReactionMeasure,
    IfcModulusOfElasticityMeasure,
    IfcMomentOfInertiaMeasure,
    IfcPlanarForceMeasure,
    IfcRotationalStiffnessMeasure,
    IfcShearModulusMeasure,
    IfcLinearMomentMeasure,
    IfcLuminousIntensityDistributionMeasure,
    IfcCurvatureMeasure,
    IfcMassPerLengthMeasure,
    IfcModulusOfLinearSubgradeReactionMeasure,
    IfcModulusOfRotationalSubgradeReactionMeasure,
    IfcRotationalMassMeasure,
    IfcSectionalAreaIntegralMeasure,
    IfcSectionModulusMeasure,
    IfcTemperatureGradientMeasure,
    IfcThermalExpansionCoefficientMeasure,
    IfcWarpingConstantMeasure,
    IfcWarpingMomentMeasure,
    IfcSoundPowerMeasure,
    IfcSoundPressureMeasure,
    IfcHeatingValueMeasure,
    IfcPHMeasure,
    IfcIonConcentrationMeasure
}
export default IfcDerivedMeasureValue