language: node_js
os: linux
node_js:
  - '8'
branches:
  only:
    - master
    - develop
    - /^release\/.*$/

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

script:
  - npm run build
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "coverage/clover.xml"

cache:
  directories:
    - node_modules