// This file was generated automatically using "ifc-syntax-codegen"
//
// Licensed under MIT by Alan Rynne
//
// Contains the following entities:
//    - IfcRevolvedAreaSolidTapered

import { IfcProfileDef, IfcAxis2Placement3D, IfcAxis1Placement, IfcRevolvedAreaSolid } from './'
import { IfcPlaneAngleMeasure } from '../types'

/** IfcRevolvedAreaSolidTapered is defined by revolving a cross section along a circular arc.
 *
 * The cross section may change along the revolving sweep from the shape of the start cross section into the shape of the end cross section.
 *
 * Corresponding vertices of the start and end cross sections are then connected.
 *
 * The bounded surface may have holes which will sweep into holes in the solid
 *
 * The rotation axis is defined by:The start cross section is defined by SELF\IfcSweptAreaSolid
 *
 * SweptArea:The end cross section is defined by EndSweptArea:The solid is generated by transforming the start cross section into to end cross section.
 *
 * A start face, an end face (each defined by start and end cross sections), and one or more lateral faces.
 *
 * Each lateral face is a ruled surface defined by a pair of corresponding edges of the start and end section.
 *
 * The ruled surfaces are constructed in the cylindrical coordinate space defined by the supertype IfcRevolvedAreaSolid
 *
 * Informal Propositions:
 */
 class IfcRevolvedAreaSolidTapered extends IfcRevolvedAreaSolid {
    constructor(SweptArea:IfcProfileDef, Position:IfcAxis2Placement3D, Axis:IfcAxis1Placement, Angle:IfcPlaneAngleMeasure, EndSweptArea:IfcProfileDef) {
        super(SweptArea, Position, Axis, Angle)
        this.EndSweptArea = EndSweptArea
    }
    /** 
    */
    EndSweptArea: IfcProfileDef
}

export default IfcRevolvedAreaSolidTapered